### ISSUE TITLE
Include committer, sha, and guesses in "rounddone" message

### ISSUE THREAD

**Issue by MikaelElkiaer** [SickTeam/GitGameServer#10] opened 2015-09-23 19:10 UTC
The "rounddone" message should look something like this:
`{ name: 'rounddone', url: '/game/{gameId}/round/{roundNo}', resource: { round: x, committer: 'deaddog', sha: 'xxx', guesses: [ ... ] }`

**Comment by deaddog** [comment] 2015-09-28 07:32
Duplicate of #4.

**Closed as completed by deaddog** 2015-09-28 07:32 UTC
Labels: duplicate, enhancement
